name: moviz_api
description: The interface and models for an API providing access to moviz.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: 1.11.0
  uuid: ^4.4.0
  
dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
